import { LineEdit, Button, VerticalBox, CheckBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window{
    width: 640px;
    height: 320px;

    title : "UMass Makerspace 3D Printing Form";

    in property<string> printer_settings : "Failed to load Printer details";
    in property<string> filament_settings : "Failed to load Filament details";
    in property<string> print_settings : "Failed to load Process details";
    in property<string> filename : "Failed to load File name";
    in property<string> print_time : "Failed to load Duration";
    in property<string> filament_weight : "Failed to load Weight";

    in property <bool> name_invalid : false;
    in property <bool> email_invalid : false;
    in property <bool> pin_invalid : false;

    callback sumbit(string, string, string, string);

    VerticalLayout {
        spacing : 10px;
        padding : 30px;
        Text {
            text: "UMass Makerspace 3D Printing Form";
            horizontal-alignment: center;
            font-size: 18pt;
        }
        HorizontalLayout {
            spacing: 20px;
            VerticalLayout {
                width : 50%;
                spacing:5px;
                VerticalLayout {
                    spacing : 3px;
                    padding : 0px;
                    human_name := LineEdit {
                        placeholder-text: "Full Name";
                    }
                    Text {
                        visible : name_invalid;
                        text : "Invalid name (alphabetic characters only)";
                        color : #dc4040;
                        horizontal-alignment: left;
                    }
                }
                VerticalLayout {
                    spacing : 3px;
                    padding : 0px;
                    email := LineEdit {
                        placeholder-text: "UMass Email";
                    }
                    Text {
                        visible : email_invalid;
                        text : "Invalid UMass email address";
                        color : #dc4040;
                        horizontal-alignment: left;
                    }
                }

                filament_owner := HorizontalBox {
                    padding : 0px;
                    spacing: 10px;

                    property<string> selected_option : "Makerspace";

                    Text {
                        text : "Filament Owner: ";
                        horizontal-alignment: right;
                    }

                    mkbox := CheckBox {
                        text : "Makerpace";
                        checked : true;
                        toggled => {
                            self.checked = true;
                            parent.selected_option = self.text;
                            psbox.checked = false;
                            /*if (self.checked) {
                                parent.selected_option = self.text;
                                psbox.checked = false;
                            } else {
                                parent.selected_option = psbox.text;
                                psbox.checked = true;
                            }*/
                        }
                    }
                    psbox := CheckBox {
                        text : "Personal";
                        checked : false;
                        toggled => {
                            self.checked = true;
                            parent.selected_option = self.text;
                            mkbox.checked = false;
                            /*
                            if (self.checked) {
                                parent.selected_option = self.text;
                                mkbox.checked = false;
                            } else {
                                parent.selected_option = mkbox.text;
                                mkbox.checked = true;
                            }*/
                        }
                    }
                }
                Rectangle {

                }
                VerticalLayout {
                    width : 50%;
                    spacing : 3px;
                    padding : 0px;
                    staff_pin := LineEdit {
                        placeholder-text: "Staff PIN";
                        input-type: password;
                    }
                    Text {
                        visible : pin_invalid;
                        text : "Invalid PIN";
                        color : #dc4040;
                        horizontal-alignment: left;
                    }
                }
            }
            VerticalLayout {
                spacing: 5px;
                /*Text {
                    text : "Print Info";
                    horizontal-alignment: center;
                    font-size: 12pt;
                }*/
                Text {
                    text : "Name: " + root.filename;
                    wrap : word-wrap;
                    color : #a29e9e;
                }
                Text {
                    text : "Printer: " + root.printer_settings;
                    wrap : word-wrap;
                    color : #a29e9e;
                }
                Text {
                    text : "Filament: " + root.filament_settings;
                    wrap : word-wrap;
                    color : #a29e9e;
                }
                Text {
                    text : "Process: " + root.print_settings;
                    wrap : word-wrap;
                    color : #a29e9e;
                }
                Text {
                    text : "Weight: " + root.filament_weight;
                    wrap : word-wrap;
                    color : #a29e9e;
                }
                Text {
                    text : "Duration: " + root.print_time;
                    wrap: word-wrap;
                    color : #a29e9e;
                }
                sumbit_button := Button {
                    text: "Submit";
                    enabled: staff_pin.text.character-count >= 4;
                    clicked => {
                        root.sumbit(human_name.text, email.text, filament_owner.selected_option, staff_pin.text);
                    }
                }
                Text {
                    font-size: 4pt;
                }
            }
        }
    }
}